# -*- coding: utf-8 -*-
"""Atividades Aula 8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iav9dD23GgIeS11orbVpBCS6dGSJ-ojO
"""

# Atividade 1
def menor (a,b):
    if a == b:
      return "Ambos são iguais."
    elif a < b:
      return a
    else:
      return b

a = input("Digite o primeiro parâmetro:")
b = input("Digite o segundo parâmetro:")
print(menor(a,b))

# Atividade 2
def negPos (n):
  if n >= 0:
    return "positivo"
  else:
    return "negativo"

n = int(input("Digite um número:"))
print(f"{n} é {negPos(n)}")

# Atividade 3
def lim (a,b,limite):
  return a + b > limite

a = int(input("Digite o primeiro parâmetro:"))
b = int(input("Digite o segundo parâmetro:"))
limite = int(input("Digite o limite:"))
print(lim(a,b,limite))

# Atividade 4
def multiplo (n):
  if n % 3 == 0 and n % 5 == 0:
    print("FizzBuzz")
  elif n % 3 == 0:
    print("Fizz")
  elif n % 5 == 0:
    print("Buzz")
  else:
    print(n)

n = int(input("Digite o número:"))
multiplo(n)

# Atividade 5
def procura (lista, n):
  return n in lista

tamanho = int(input("Defina o tamanho da lista:"))
lista = []
while (len(lista) < tamanho):
  lista.append(int(input("Digite um dos números da lista:")))

n = int(input("Digite um número a procurar"))
print(procura(lista, n))

# Atividade 6
def soma (n):
  i = 0
  soma = 0
  while (i<=n):
    soma += i
    i += 1
  return soma

n = int(input("Digite um inteiro positivo:"))
print(soma(n)) if n >= 0 else print("Número inválido")

